booking/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'booking'

urlpatterns = [
    url('novo_booking/', views.novo_booking, name='novo_booking'),
    url('minhas_reservas/', views.minhas_reservas, name='minhas_reservas')
]

projectSAS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

app_name = 'peoject'

urlpatterns = [
    path('admin/', admin.site.urls),
    url('user/', include('user.urls')),
    url('booking/', include('booking.urls')),
    url('index/', include('sas.urls', namespace='sas')),
    url('', include('sas.urls'))
]

sas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'sas'

urlpatterns = [
    #url('teste/', views.teste)
    url('user/', include('user.urls', namespace='user')),
    url('', views.index, name='index')
]

user/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    #url('teste/', views.teste),
    url('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(template_name='sas/index.html'), name='logout'),
    url('novo_usuario/', views.novo_usuario, name='novo_usuario')
]

sas/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, '../templates/sas/index.html')

sas/templates/sas/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/css.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'booking:novo_booking' %}">Cadastrar Reserva</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'sas:index' %}">Home<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#">Pesquisar Lugares</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'booking:minhas_reservas' %}">Minhas reservas</a>
                </li>
              {% endif %}
            </ul>
            <span class="navbar-text">
              <i class="fas fa-user"></i>
              <!-- <a href="{% url 'user:login' %}"></a> -->
                  <!-- <button class="btn btn-info">Login</button> -->
              <!-- </a> -->
              <!-- <button class="btn btn-info" data-toggle="modalLogin" data-target="#modalLogin">Login</button> -->
              <!-- <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
                Login
              </button> -->
              {% if user.is_authenticated %}
              <a href="{% url 'user:logout' %}">
                <button class="btn btn-danger">Logout</button>
              </a>
              {% else %}
              <a href="{% url 'user:novo_usuario' %}">
                <button class="btn btn-info">Cadastrar</button>
              </a>
              <a href="{% url 'user:login' %}">
                <button class="btn btn-info">Logar</button>
              </a>
              {% endif %}
            </span>
          </div>
        </nav>
        <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      </div>
                  <div class="modal-body">
                  ...
                  </div>
                      <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <a href="{% url 'user:novo_usuario' %}">
                        <button type="button" class="btn btn-primary">Cadastrar</button>
                      </a>
                  </div>
              </div>
          </div> -->
        </div>
        {% block conteudo %}
        {% endblock %}
        <script src="{% static 'js/jquery-3.4.1.min.js' %}">
          {% block script %}
          {% endblock %}
        </script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

sas/templates/sas/home.html
{% extends 'sas/base.html' %}
{% load static %}
{% block conteudo %}
    <h2>home html</h2>
{% endblock %}

sas/templates/sas/index.html
{% extends 'sas/base.html' %}
{% load static %}
{% block conteudo %}
    <h2>bem vindo INDEX.html</h2>
{% endblock %}